//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TodoProject.Resources.Models {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TodoItem {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TodoItem() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TodoProject.Resources.Models.TodoItem", typeof(TodoItem).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategori en fazla 20 karakter alabilir..
        /// </summary>
        public static string Category_Length {
            get {
                return ResourceManager.GetString("Category_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategori alanı boş bırakılamaz..
        /// </summary>
        public static string Category_Required {
            get {
                return ResourceManager.GetString("Category_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Açıklama en fazla 500 karakter olabilir..
        /// </summary>
        public static string Description_Length {
            get {
                return ResourceManager.GetString("Description_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitiş tarihi giriniz..
        /// </summary>
        public static string DueDate_Required {
            get {
                return ResourceManager.GetString("DueDate_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diğer kategori en fazla 20 karakter olabilir..
        /// </summary>
        public static string OtherCategoryMaxLength {
            get {
                return ResourceManager.GetString("OtherCategoryMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen diğer kategoriyi giriniz..
        /// </summary>
        public static string OtherCategoryRequired {
            get {
                return ResourceManager.GetString("OtherCategoryRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öncelik alanı seçilmelidir..
        /// </summary>
        public static string Priority_Required {
            get {
                return ResourceManager.GetString("Priority_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Durum alanı seçilmelidir..
        /// </summary>
        public static string Status_Required {
            get {
                return ResourceManager.GetString("Status_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başlık en fazla 50 karakter olabilir..
        /// </summary>
        public static string Title_Length {
            get {
                return ResourceManager.GetString("Title_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başlık alanı boş bırakılamaz..
        /// </summary>
        public static string Title_Required {
            get {
                return ResourceManager.GetString("Title_Required", resourceCulture);
            }
        }
    }
}
